### PR TITLE
Auto updated assets for ansible collection eng

### PR DESCRIPTION
**Pull request by yograjshisode**

### CODE REVIEW

**Comment by sabandi** [comment]
@amolopcito can you please look into this failure.

**Comment by yograjshisode** [comment]
run auto-merge

**Comment by yograjshisode** [comment]
run auto-merge

**Comment by yograjshisode** [comment]
run auto-merge

**Comment by yograjshisode** [comment]
run auto-merge

**Review by sabandi — APPROVED** [review]

**Pull request merged**
